name: FAIR Data Point Submission
description: Use this form to submit new FAIR Data Point data for inclusion in the triple store.
title: "FDP Submission: [Title]"
body:
  - type: markdown
    attributes:
      value: "## Basic Information"
  - type: input
    attributes:
      label: Title
      description: "Enter the title of the dataset or resource."
      placeholder: "Example: Duchenne Parent Project: FAIR Data"
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      description: "Enter the version of the dataset."
      placeholder: "Example: 1.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: "Provide a brief description of the dataset."
      placeholder: "Clinical and Patient Reported data for Duchenne and Becker muscular dystrophy patients."
    validations:
      required: true
 - type: input
   attributes:
     label: Publisher
     description: "Enter a URI that depicts the publisher of the resource"
     placeholder: "http://www.wikidata.org/entity/Q28381786"
   validations:
     required: true
